name: darktable
grade: devel
version: "2.2.0rc0"
summary: photo worklow software
description: |
  darktable is an open source photography workflow application
  and RAW developer

confinement: devmode

apps:
    darktable:
        command: desktop-launch darktable --moduledir $SNAP/lib/darktable --datadir $SNAP/share/darktable --localedir $SNAP/share/locale --configdir $SNAP_USER_DATA
        plugs: [home, unity7, x11, gsettings]

parts:
    darktable:
        source: git://github.com/darktable-org/darktable.git
        source-type: git
        source-tag: release-2.2.0rc0
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
        build-packages:
            - g++
            - intltool
            - libcaca-dev
            - libcolord-dev
            - libcolord-gtk-dev
            - libcups2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libexiv2-dev
            - libflickcurl-dev
            - libgnome-keyring-dev
            - libgphoto2-dev
            - libgraphicsmagick1-dev
            - libgtk-3-dev
            - libjpeg-dev
            - libjson-glib-dev
            - liblcms2-dev
            - liblua5.2-dev
            - liblensfun-dev
            - libopenjpeg-dev
            - libosmgpsmap-1.0-dev
            - libpugixml-dev
            - libpulse-dev
            - libraptor1-dev
            - libreadline-dev
            - libreadline6-dev
            - librsvg2-dev
            - libsdl1.2-dev
            - libsecret-1-dev
            - libslang2-dev
            - libsoup2.4-dev
            - libsqlite3-dev
            - libtinfo-dev
            - libtiff5-dev
            - libudev-dev
            - libwebp-dev
            - libxml2-dev
            - libxml2-utils
            - libxslt1-dev
            #- openjdk-8-jre
            - xsltproc
        after: [desktop-gtk3]
