name: darktable
version: 1
summary: photo worklow software
description: |
  darktable is an open source photography workflow application
  and RAW developer

confinement: devmode

apps:
    darktable:
        command: desktop-launch darktable --moduledir $SNAP/lib/darktable --datadir $SNAP/share/darktable
        plugs: [home, unity7, x11, gsettings]

parts:
    darktable:
        source: git://github.com/darktable-org/darktable.git
        source-type: git
        plugin: cmake
        configflags:
            - -DRUNTIME_INSTALL_PREFIX=/snap/darktable/current
#            - -DCMAKE_INSTALL_PREFIX=/snap/darktable/current
        build-packages:
            - intltool
            - xsltproc
            - libgtk-3-dev
            - libxml2-utils
            - libxml2-dev
            - liblensfun-dev
            - librsvg2-dev
            - libsqlite3-dev
            - libcurl4-gnutls-dev
            - libjpeg-dev
            - libtiff5-dev
            - liblcms2-dev
            - libjson-glib-dev
            - libexiv2-dev
            - libpugixml-dev
            - libgphoto2-dev
            - libwebp-dev
        stage-packages:
            - fontconfig-config
            - fonts-freefont-ttf
            - shared-mime-info
            - libgtk-3-bin
        after: [desktop/gtk3]
